# Generated by Django 3.0.3 on 2021-03-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0058_person_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='editable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='editable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='properties',
            name='editable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='editable',
            field=models.IntegerField(default=0),
        ),
    ]
