# Generated by Django 3.0.3 on 2021-03-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0059_auto_20210323_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(blank=True, default='Saved', max_length=10),
        ),
    ]
