# Generated by Django 3.0.3 on 2021-03-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0060_auto_20210327_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='extension',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), (' no', ' no')], max_length=4, null=True),
        ),
    ]
