# Generated by Django 3.0.3 on 2021-03-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0061_site_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='extension',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=4, null=True),
        ),
    ]
